server/package.json
서버 구동을 위한 pm2 패키지 및 시작 스크립트 추가
=> pm2 패키지 추가

client/src/App.js, client/src/component/Navbar.js, client/src/pages/calendarPage.js, client/src/pages/homePage.js, client/src/pages/listPage.js, client/src/pages/statisticsPage.js, client/src/router.js, client/src/util/util.js
SPA 라우터를 구현했습니다!
달력페이지, 통계페이지 구현해봅시다 ㅎㅎ
=> 홈페이지, 내역페이지, 달력페이지, 통계페이지 라우터 추가

client/src/App.js, client/src/component/Form.js, client/src/component/Form.scss, client/src/component/Ledger.js, client/src/component/LedgerItem.js, client/src/router.js, client/src/store.js, client/src/util/util.js
=> Form 태그 가계부 항목 추가 함수 구현

server/app.js, server/controller/payment-controller.js, server/controller/transaction-controller.js, server/http/transactionApi.http, server/model/payment.js, server/model/transaction.js, server/route/payment-router.js, server/route/transaction-router.js
[API 설계](https://github.com/woowa-techcamp-2020/hkb-6/wiki/%F0%9F%93%9D-api-%ED%98%95%EC%8B%9D)을 참고하여 `GET`, `POST` transaction API를 구현했습니다.
=> Transaction GET, POST  API 구현

client/src/component/Form.js, client/src/component/Form.scss, client/src/scss/main.scss, client/src/store.js, server/db.js
form submit 관련하여 유효성 검사와 관련된 함수 추가 및 css, 기존 기능 관련 버그 수정
=> Form submit 관련 함수 구현

client/src/Data.js, client/src/component/Filter.js, client/src/component/Filter.scss, client/src/component/Header.js, client/src/component/Ledger.js, client/src/component/LedgerItem.js, client/src/component/LedgerItem.scss, client/src/component/Modal.js, client/src/scss/_variable.scss, client/src/scss/main.scss, client/src/service/paymentService.js, client/src/store.js, server/model/payment.js
#10 
내역페이지의 컴포넌트 중 `<Ledger>` 컴포넌트를 구현했습니다
=> Ledger 컴포넌트 기능 구현

client/.env.dev, client/.env.prod, client/.gitignore, client/src/.sample.env.dev, client/src/.sample.env.prod, client/src/service/paymentService.js, client/src/store.js
=> Client 개발 환경변수와 프로덕션 환경변수 분리

client/.env.dev, client/src/component/Form.js, client/src/component/Form.scss, client/src/store.js, client/src/util/validation.js
1. 금액 입력칸에 콤마를 붙이는 함수 구현 후 데이터로 들어갈 때 콤마를 제거하지 않아 NaN 으로 입력되는 버그를 해결했습니다.
2. 기존의 새로 만들어지는 tmp[curdate]["amount"]에 변경된 데이터를 넣는 코드 부분이 잘못되어 수정했습니다
closes #42
=> 금액 입력 제대로 안되는 버그 수정

client/.env.dev, client/src/Data.js, client/src/component/Filter.js, client/src/component/Ledger.js, client/src/component/LedgerItem.js, client/src/component/LedgerItem.scss, client/src/scss/main.scss, client/src/util/constant.js, client/src/util/util.js
Filter 컴포넌트의 기능을 구현했습니다
-  수입/ 지출 선택여부에 따라 해당하는 내역을 보여줍니다
-  Label 옆에 월간 수입/지출 총액을 표시합니다
=> Filter 컴포넌트 기능 구현

client/src/component/CategoryList.js, client/src/component/Form.js, client/src/component/LedgerItem.js, client/src/component/Navbar.scss, client/src/router.js, client/src/util/util.js, server/route/api-router.js
- dom element찾는 util함수 추가 및 적용
- 수입/지출에 따라 다른 카테고리 항목 보이도록 구현
- navbar scss 수정
closes #53
=> [Form feature] 수입/지출에 따라 다른 카테고리 항목 보이도록 구현

client/src/component/Calendar.js, client/src/component/CalendarDay.js, client/src/component/Form.js, client/src/component/Ledger.js, client/src/component/LedgerItem.js
=> [버그수정] #65	unsubscribe 버그 수정

client/src/Data.js, client/src/component/PieChart.js, client/src/component/PieChart.scss, client/src/component/StatisticsMenu.js, client/src/pages/statisticsPage.js, client/src/util/constant.js, client/src/util/util.js, server/sql_scripts/createTable.sql
Mock data를 이용해 piechart를 그렸습니다.
- percentage 에 따라 pie를 나누었습니다.
- 각 pie별로 label을 붙였습니다.
=> Piechart 컴포넌트 구현

server/controller/payment-controller.js, server/controller/transaction-controller.js, server/model/payment.js, server/model/transaction.js, server/route/payment-router.js, server/utils/contant.js
요청에 담아 보낸 `token`을 이용해 유저를 식별하고
식별된 유저에 해당하는 정보를 create, read 할 수 있도록 쿼리를 수정했습니다.
=> [기능개선] 로그인된 유저의 정보를 가져오는 기능 구현

client/src/component/Calendar.js, client/src/component/CalendarDay.js, client/src/component/Form.js, client/src/component/Ledger.js, client/src/component/LedgerItem.js, client/src/pages/listPage.js, client/src/router.js, client/src/store.js, client/src/util/sumCalculator.js, client/src/util/util.js, server/model/transaction.js
- 월간 이동 이벤트 발생 시, toPrevMonth, toNextMonth에서 ledgerItem을 fetch하는 로직 추가
- login상태(jwt 토큰 유무 상태)확인하는 유틸 함수 추가
- login 상태에 따라 index url에서 보여주는 뷰 변경
- GET `/transaction` api에서 레코드가 없을 때, 빈 문자열 돌려주는 로직 추가
=> [기능개선] navbar에서 월간이동 시 ledger가 해당 달에 데이터를 보여주도록 로직 수정

client/src/component/Bargraph.js, client/src/component/Calendar.js, client/src/component/LineGraph.js, client/src/component/LineGraph.scss, client/src/component/PieChart.js, client/src/component/StatisticsMenu.js, client/src/store.js
statistics menu에서 라디오 버튼을 어떤 것을 클릭하냐에 따라서  bar graph와 line graph를 번갈아 보여주는 기능을 구현
- 카테고리별 지출 라디오버튼 클릭시 bar graph 보여주는 기능 구현
- 일별 지출 라디오버튼 클릭시 line graph 보여주는 기능 구현
=> [statistics menu] 라디오 버튼 클릭으로 bar, line graph을 토글로 보여주는 기능 구현

client/src/component/Calendar.js, client/src/component/Form.js, client/src/component/Ledger.js, client/src/component/LedgerItem.js, client/src/component/LedgerItem.scss, client/src/pages/calendarPage.js, client/src/service/transactionService.js, client/src/store.js, client/src/util/util.js, server/controller/transaction-controller.js, server/model/transaction.js
- `ledger-item-record`  element에 `mouserover` 이벤트 발생 시 수정 버튼 보여주기
- `ledger-item-record`  element에 `mouseover` 이벤트 발생 시 `background-color` 변경하기
- `ledger-item-record`  element에 `mouseout`이벤트 발생 시 수정 버튼 가리기
- `ledger-item-record`  element에 `mouseout`이벤트 발생 시 `background-color` 원상 복구
-  `update-record-btn` element에 `click`이벤트 발생 시 record 내용을 `Form` component에 넣어주기
=> [기능추가] ledger Item 컴포넌트 수정 기능 구현

client/src/component/Bargraph.js, client/src/component/PieChart.js, client/src/pages/statisticsPage.js, client/src/service/statisticsService.js, client/src/store.js, server/controller/statistics-controller.js, server/http/statisticsApi.http, server/model/transaction.js, server/route/statistics-router.js
- 월간  카테고리별 합계 및 백분율을 반환하는 API 구현
-  Client와 연동
=> GET statistics api 구현

client/src/component/Form.js, client/src/component/Form.scss, client/src/component/LedgerItem.js, client/src/component/LedgerItem.scss, client/src/component/LineGraph.js, client/src/component/LineGraph.scss, client/src/pages/listPage.js
- [css] #92 내용지우기 버튼 css 추가
- [css] #92 line bar 애니메이션 수정
- [기능추가] list item #92 수정 버튼 클릭시 상단으로 스크롤하도록 구현
- [css] edit 버튼 #92 edit버튼 스타일 수정
- [기능개선] line bar #92 만원이하 금액시 0으로 표시되도록 버그 수정함
=> list page style 추가 및 line bar 버그 수정, edit버튼 클릭시 화면 상단 스크롤 구현

client/src/component/Filter.js, client/src/component/Navbar.js
=> [버그수정] #94 calendar, statistics 페이지에서 달력 이동시 filter의 총액이 바뀌지 않는 버그 수정

server/app.js, server/config/logger-config.js, server/package.json
API 서버로 들어오는 요청에 대해 로그를 남기고 file에 기록해서 저장할 수 있는 로직 추가
=> [기능추가] 서버에서 pm2, morgan을 이용해 로그를 기록하는 로직 추가

client/src/component/Form.js
=> [버그수정] #100 Form 컴포넌트 select 유효성 검사 버그 수정
